# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: tommyoh0428
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-nodejs-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-nodejs-api
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    DATABASE_URL: ${env:DATABASE_URL, "fallback value"}

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: "*"

# can exclude sensitive information from being deployed
custom:
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - DATABASE_URL

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
